// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgebbseyocknxgtchywg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnZWJic2V5b2NrbnhndGNoeXdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MjAxNTksImV4cCI6MjA3MzI5NjE1OX0.qXCbuhTltyWIB2uhRfTeoxQFMRrsSf9seAdsiYgh8_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});